### ISSUE TITLE
The examples are confusing/not working

### ISSUE THREAD

**Issue by DragonFIghter603** [Articdive/JNoise#1]
### What is the current behavior?
The examples in the README.md don't seem to work on the latest maven version (3.0.2).
They also don't seem to be syntactically correct.

### What is the expected behavior?
The examples should be up to date and working simply by copy pasting them, without having to change anything
except of course import stuff.

### What steps will reproduce the problem?
Try to copy paste the examples into a new project, most of them don't seem to work at all or only when modifying them.

### What operating system and java version is being used?
Java 17, windows 10

### If there is an exception, use pastebin (no expiry date) to send the stacktrace:
---

### Additional information / Possible thoughts on why this bug is happening:
The examples either seem to have not been updated or are already updated to the currently in-dev version.

**Comment by Articdive** [comment]
Should be fixed now; I was not uploading version 4.0.0-SNAPSHOT to the snapshot repository due to a bug in Gradle, I never checked if my build every went through.

Please note that you will need to follow the steps in the README again. The documentation is for version 4.0.0-SNAPSHOT. If you want the documentation for version 3.2.0 you should check the github tag and see the commit where it was released.
