### ISSUE TITLE
When using octaves with fast simplex, the noise value fails to reach significant values

### ISSUE THREAD

**Issue by Flopgop** [Articdive/JNoise#4]
### What is the current behavior?
Octavation causes noise to never go above 0.4 (or they do for insignificant distances.)

### What is the expected behavior?
I expect the noise to still be able to reach significant values (as it does with FastNoiseLite for example.)

### What steps will reproduce the problem?
Using the pipeline,
```java
var pipeline = JNoise.newBuilder()
                .fastSimplex(seed, Simplex2DVariant.CLASSIC, Simplex3DVariant.IMPROVE_XZ, Simplex4DVariant.IMPROVE_XYZ_IMPROVE_XZ)
                .octavate(3, 0.5, 2.0, FractalFunction.FBM, false)
                .build();
```
Then sample a couple values

### What operating system and java version is being used?
Manjaro Linux latest
Openjdk version "17.0.7" 2023-04-18

### Additional information / Possible thoughts on why this bug is happening:
This could be because subsequent octaves can have negative values and therefore lower the first octave's value. This definitely could be expected behavior however so please let me know.

**Comment by Articdive** [comment]
Which version of JNoise are you using?

**Comment by Articdive** [comment]
So when octiviation happen we do the following (in somewhat pseudocode):
Keep in mind your gain is 0.5.
```
result = 0
result += gain * noise(frequency * position)
result += gain^2 * noise(frequency * lacunarity * position)
result += gain^3 * noise(frequency * lacunarity^2 * position)
```

Since your gain is 0.5, you will get half of the original function, and then 0.25 of the next, 0.125 of the next and so on.

Theoretically I could define the function to begin as follows:
```
result = noise(frequency * position)
result += gain^1 * noise(frequency * lacunarity * position)
result += gain^2 * noise(frequency * lacunarity^2 * position)
```

I believe that would solve the issue you are having. There is no real literature for the 'correct' way to do this. Maybe since the second formula looks a bit nicer, however having the gain applied first, keeps the noise value in an interval, that most people use [-1, 1] or [0, 1].

I will think about changing it, but it is not a bug from my identification, please let me know otherwise if you disagree or have relevant points :)
